name: comiko_shared
description: Shared components for Comiko.
version: 0.0.1

environment:
  sdk: ">=1.24.1 <2.1.0"

dependencies:
  json_annotation: "^1.1.0"

dev_dependencies:
  json_serializable: "^1.2.1"
  build_runner: "^0.10.1+1"
  build_test: "0.10.3+1"
  test: "^1.3.0"

