name: comiko_shared
description: Shared components for Comiko.
version: 0.0.1

environment:
  sdk: '>=1.24.1 <2.1.0'

dependencies:
  json_annotation: ^0.2.2

dev_dependencies:
  json_serializable: "^0.3.1"
  build_runner: ^0.7.4
  test: ^0.12.30
